config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resource :users, controller: 'registrations', only: [:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end


  resource :users, controller: 'sessions', only: [] do
    get '/sign_in' , action: 'new'
    post '/sign_in' , action: 'create'
    delete '/sign_out' , action: 'destroy'
  end



  resources :boards do
    member do
      patch :hide
      patch :open
      patch :lock
    end
    resources :posts, shallow: true
  end

  resources :posts, only:[] do
    resources :comments, shallow: true, only: [:create, :destroy]
    member do
      post :favorite
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  acts_as_paranoid
  include AASM

  validates :title, presence: true, length: { minimum: 4 }

  has_many :posts
  belongs_to :user, optional: true


  aasm(column: 'state', no_direct_assignment: true) do
    state :open, initial: true
    state :hidden, :locked

    event :hide do
      transitions from: :open, to: :hidden

      # 發簡訊
      after do
        puts "發簡訊!!"
      end
    end

    event :lock do
      transitions from: :open, to: :locked
    end

    event :open do
      transitions from: [:locked, :hidden], to: :open
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  belongs_to :post

  default_scope { order(id: :desc) }

  validates :content, presence: true



end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  belongs_to :board
  belongs_to :user
  has_many :comments
  has_many :favorite_posts
  has_many :favorite_users, through: :favorite_posts, source: 'user'

  validates :title, presence: true
  validates :content, presence: true

  def owned_by?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /[\w]+@([\w-]+\.)+[\w-]{2,4}/ }
  validates :password, presence: true,
                       confirmation: true,
                       length: { minimum: 4 }
  validates :nickname, presence: true

  before_create :encrypt_password

  has_many :posts
  has_many :comments
  has_many :favorite_posts
  has_many :my_favorites, through: :favorite_posts, source: 'post'
  has_many :boards

def self.login(user)
  pw = Digest::SHA1.hexdigest("a#{user[:password]}z")
  User.find_by(email: user[:email], password: pw)
end

def favorite?(post)
  my_favorites.include?(post)
end


  private
  def encrypt_password
    self.password = Digest::SHA1.hexdigest("a#{self.password}z")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pundit
  
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  
  def session_required
    redirect_to sign_in_users_path, notice: '請先登入會員' if not user_signed_in?
  end

  def record_not_found
    render file: 'public/404.html',
           layout: false,
           status: :not_found
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only: [:show, :edit, :update, :destroy, :hide, :open, :lock]

  def index
    @boards = Board.all
  end

  def show
    @posts = @board.posts.order(id: :desc)
  end

  def new
    @board = Board.new
  end

  def create
    # @board = Board.new(board_params)
    @board = current_user.boards.new(board_params)

    if @board.save
      redirect_to "/", notice: '成功新增看板'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to root_path, notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to root_path, notice: '看板已刪除'
  end

  def hide
    authorize @board, :hide?
    @board.hide! if @board.may_hide?
    redirect_to boards_path, notice: '看板已隱藏'
  end

  def open
    @board.open! if @board.may_open?
    redirect_to boards_path, notice: '看板已開放'
  end

  def lock
    @board.lock! if @board.may_lock?
    redirect_to boards_path, notice: '看板已鎖'
  end


  private
  def find_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :session_required
  before_action :find_post, only: [:create]

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post
    
    if @comment.save
      # redirect_to @post
      render text:'hi'
    else
      render 'posts/show'
    end
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    comment.destroy
    redirect_to comment.post, notice:'留言已刪除'
  end


  private
  def find_post
    @post = Post.find(params[:post_id])
  end


  def comment_params
    params.require(:comment).permit(:content)
  end
end 

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.login(params[:user])
    if user
      session[:user9527] = user.id
      redirect_to root_path, notice:'登入成功'
    else
      redirect_to sign_in_users_path, notice:'登入失敗'
    end
  end

  def destroy
    session[:user9527] = nil
    redirect_to root_path, notice: '已登出!'
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_board, only: [:new, :create]
  before_action :session_required, only: [:create, :edit, :update]
  before_action :save_post, only: [:show]


  def show

    @comment = Comment.new
    @comments = @post.comments.includes(:user).page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    # @post.board = @board
    # @post.user = current_user

    @post = current_user.posts.new(post_params)
    @post.board = @board


    if @post.save
      redirect_to boards_path(@board), notice:'新增文章成功'
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: '文章更新成功'
    else
      redirect_to :edit
    end
  end

  def favorite
    post = Post.find(params[:id])
    if current_user.favorite?(post)
      current_user.my_favorites.destroy(post)
      render json: { status: 'removed' }
    else
      current_user.my_favorites << post
      render json: { status: 'added' }
    end

  end


  

  private
  def set_board
    @board = Board.find(params[:board_id])
  end


  def post_params
    params.require(:post).permit(:title, :content)
  end

  def save_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  
  before_action :session_required, only:[:edit, :update]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'OK!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_users_path, notice: '資料更新成功'
    else
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def board_title_css(board)
    "board-title board-title-#{board.state}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user9527].present?
      @_user9487 ||= User.find_by(id: session[:user9527])
    else
      nil
    end
  end

  def user_signed_in?
    if current_user
      return true
    else
      return false
    end
  end
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
    <% board.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(board) do |form| %>
  <%= form.label :title, '看板標題' %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>

<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<h1>看板列表</h1>

<%= link_to "新增看板", new_board_path %>

<ul>
<% @boards.each do |board| %>
  <li>
    <%= link_to "編輯", edit_board_path(board) %>
    <%= link_to "刪除", board,
                        method: 'delete',
                        data: { confirm: '是否確定刪除？' } %>


    <%= link_to '隱藏', hide_board_path(board), method: 'patch' if board.may_hide? && policy(board).hide? %>
    <%= link_to '開放', open_board_path(board), method: 'patch' if board.may_open? &&policy(board).open? %>
    <%= link_to '鎖定', lock_board_path(board), method: 'patch' if board.may_lock? && policy(board).lock? %>
    
    <%= link_to board.title, board, class: board_title_css(board) %>
  </li>
<% end %>
</ul>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>

<%= link_to '新增文章', new_board_post_path(@board) %>


<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>

app/views/comments/_comment.html.erb
<li>
  [<%= comment.user.nickname %>]
  <%= comment.content %>
  <%= link_to '刪除', comment, method: 'delete', data:{confirm: '確認刪除？'} %>
</li>

app/views/comments/create.js.erb
var comment_area = document.querySelector('.comment');
comment_area.innerHTML = "<%= j render('comments/comment', comment: @comment) %>" + comment_area.innerHTML;

document.querySelector('#comment_content').value = '';

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZCard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" if flash["notice"] %>
    <section class="main-section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編輯文章</h1>

<%= form_for(@post) do |form| %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :content %>
  <%= form.text_area :content %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/posts/new.html.erb
<h1>新增文章</h1>

<%= form_for(@post, url: board_posts_path(@board)) do |form| %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :content %>
  <%= form.text_area :content %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/posts/show.html.erb
<h2 data-controller="favorite" data-favorite-id="<%= @post.id %>">
  <% if user_signed_in? %>
    <%= link_to '#', data: { action: 'favorite#go' } do %>
      <% if current_user.favorite?(@post) %>
        <i class="fas fa-heart" data-target="favorite.icon"></i>
      <% else %>
        <i class="far fa-heart" data-target="favorite.icon"></i>
      <% end %>
    <% end %>
  <% end %>
</h2>

<h2><%= @post.user.nickname %></h2>
<h1><%= @post.title %></h1>

<%= link_to '編輯', edit_post_path(@post) if @post.owned_by?(current_user) %>

<article>
  <%= simple_format(@post.content) %>
</article>

<%= link_to '回上頁', :back %>

<%= form_for(@comment, url: post_comments_path(@post), remote: true) do |f| %>
  <%= f.text_area :content, placeholder: '請輸入留言' %>
  <%= f.submit '送出' %>
<% end %>

<ul class="comment">
<%= render @comments %>
</ul>
<%= paginate @comments %>

app/views/shared/_flash.html.erb
<p><%= flash["notice"] %></p>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "首頁", root_path %></li>
    <li><%= link_to "看板列表", boards_path %></li>
  </ul>
  <ul>
    <% if current_user %>
      <li><%= current_user.nickname %></li>
      <li><%= link_to "登出", sign_out_users_path, method: 'delete' %></li>
    <% else %>
      <li><%= link_to "註冊", sign_up_users_path %></li>
     <li><%= link_to "登入", sign_in_users_path %></li>
    <% end %>
  </ul>
</nav>